name: Generate Terraform Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - '**'
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.yaml'

jobs:
  generate-docs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform docs and graph
        run: |
          README="README.md"
          GRAPH_DIR=".tfdoc-assets"
          GRAPH="$GRAPH_DIR/terraform-dependency-graph.png"
          
          # Clear existing files
          rm -f $README $GRAPH
          mkdir -p $GRAPH_DIR
          
          # Generate dependency graph
          echo "## Terraform Dependency Graph" >> $README
          terraform graph | dot -Tpng -o $GRAPH || { echo "Failed to generate graph"; exit 1; }
          echo "![Terraform Graph]($GRAPH)" >> $README
          
          # Append Terraform documentation
          echo -e "\n## Terraform Documentation" >> $README
          terraform-docs markdown table . >> $README || { echo "Failed to generate docs"; exit 1; }
          
          # Output README for verification
          cat $README || { echo "Failed to display README"; exit 1; }

      - name: Commit generated docs (only on push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Terraform Docs" --no-verify
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD
