name: Generate Terraform Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - '**'
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  generate-docs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform docs and graph
        run: |
          README="README.md"
          GRAPH_DIR=".tfdoc-assets"
          GRAPH="$GRAPH_DIR/terraform-dependency-graph.png"

          rm -f $README $GRAPH
          mkdir -p $GRAPH_DIR

          echo "## Terraform Dependency Graph" >> $README
          terraform graph | dot -Tpng -o $GRAPH
          echo "![Terraform Graph]($GRAPH)" >> $README
          
          echo -e "\n## Terraform Documentation" >> $README
          terraform-docs markdown table . >> $README

          cat $README

      - name: Commit generated docs (only on push)
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Terraform Docs"
          git push
