name: Generate Terraform Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - '**'
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  generate-docs:
    runs-on: self-hosted
    permissions:
       contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       # with: 
        #  token: $ {{ secrets.GH_TOKEN }}
          
      - name: Triggering Actor
        run: |
           echo "Workflow triggerd by: ${{ github.actor }}"
           echo "Event: ${{ github.event_name }}
      
      - name: Initialize Terraform 
        run: terraform init

      - name: Generate Terraform docs and graph 
        run: |
          README="README.md"
          GRAPH_DIR=".tfdoc-assets"
          GRAPH="$GRAPH_DIR/terraform-dependency-graph.png"

          rm -f $README $GRAPH
          mkdir -p $GRAPH_DIR
          echo "## Terraform Dependency Graph" >> $README
          terraform graph | dot -Tpng -o $GRAPH
          echo "![Terraform Graph]($GRAPH)" >> $README
          
          echo -e "\n## Terraform Documentation" >> $README
          terraform-docs markdown table . >> $README

          cat $README

      - name: Commit generated docs (only on push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          sudo git config --global user.name "Terraform Docs Bot "
          sudo git config --global user.email "terraform-docs-bot@users.noreplay.github.com"
          sudo git add README.md .tfdoc-assets/
          
          if ! sudo git diff --quiet --staged: then 
            sudo git commit -m "Auto-update: Terraform Docs" 
            sudo git push " https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          else 
             echo "no change to commit."
          fi   
