name: Generate Terraform Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - '**'
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  generate-docs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform docs and graph
        run: |
          README="README.md"
          GRAPH_DIR=".tfdoc-assets"
          GRAPH="$GRAPH_DIR/terraform-dependency-graph.png"

          rm -f $README $GRAPH
          mkdir -p $GRAPH_DIR
          echo "## Terraform Dependency Graph" >> $README
          terraform graph | dot -Tpng -o $GRAPH
          echo "![Terraform Graph]($GRAPH)" >> $README
          
          echo -e "\n## Terraform Documentation" >> $README
          terraform-docs markdown table . >> $README

          cat $README

      - name: Commit generated docs (only on push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          #git config user.name "github-actions"
          #git config user.email "github-actions@github.com"
          sudo git config --global user.name "even-tempered"
          sudo git config --global user.email "saurabhdeshmukh2110@gmail.com"
          sudo git add README.md
          sudo git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Terraform Docs" --no-verify
          sudo git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          sudo git push origin HEAD
